[build-system]
requires = ["hatchling>=1.12.0"]
build-backend = "hatchling.build"

[project]
name = "da_pipeline"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
  "dagster>=1.10.14",
  "dagster-webserver>=1.10.14",
  "pydantic>=2.11.4",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.3.5",
  "black>=25.1.0",
  "mypy>=1.15.0",
]

[tool.hatch.build]
packages = ["da_pipeline"]
exclude = ["da_pipeline_tests"]

[tool.hatch.build.targets.wheel]
include = ["da_pipeline/**"]

[tool.dagster]
module_name = "da_pipeline"
