name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  setup-dev-shell:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install Nix with Flakes support
      - name: Install Nix
        uses: cachix/install-nix-action@v31

     # Set up Nix Flakes shell environment
      - name: Set up shell environment
        run: |
          nix develop --command true
